# Generated by Django 4.1.3 on 2023-01-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.BigAutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
