# Generated by Django 4.1.4 on 2022-12-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
