# Generated by Django 4.1.3 on 2023-02-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0017_remove_reservations_discounted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='dayTime',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Whole Day', 'Whole Day')], max_length=150),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservation.customer'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservation.discount'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
